### ISSUE TITLE
Wild Pokemon can steal held items via Thief

### ISSUE THREAD

**Issue by BenjaminEHowe** [cRz-Shadows/Pokemon_Crystal_Legacy#13]
In vanilla Crystal it isn't possible for wild Pokemon to know thief as it's TM-only. In Gen 3 wild Pokemon no longer steal held items. This means that the held item will be lost if it isn't stolen back or the wild Pokemon isn't caught.

**Comment by cRz-Shadows** [comment]
Well the only pokemon that learn it is sentret and furret, and I know sentret can't be found at the level where it can learn theif. I suppose the furrets on route 1 probably can.

**Comment by BenjaminEHowe** [comment]
> Well the only pokemon that learn it are sentret and furret, and I know sentret can't be found at the level where it can learn theif

I'm 95% sure that the Furret on route 43 (Lv.21, morning and day only) know it, although I could be mis-remembering.

> you logically would never have an exp share mon out in front to lose anyway

No, I don't know anybody who would do that... 🙈 (it wasn't intentional, I just wasn't thinking too carefully while training!)

**Comment by cRz-Shadows** [comment]
You are right route 41 too yeah. I'll be honest, this is the kind of thing that's so minor that it's not worth releasing a new patch for it tbh. But if there's an elegant solution without really changing furret's moveset and there ends up being a need for another bug fix patch anyway, I can implement some fix.

**Comment by BenjaminEHowe** [comment]
Oh for sure -- it's definitely mainly me being a muppet rather than a "serious" bug. Heck, arguably it's not even a bug given that wild Pokemon no longer stealing held items wasn't introduced until gen 3.

I'll leave it up to you as to if or how this is fixed. I'd love to offer a PR with a proposed fix, but the last time I wrote assembly would probably be 8 years ago...
