### ISSUE TITLE
Bite shows as GHT type with move reminder

### ISSUE THREAD

**Issue by BenjaminEHowe** [cRz-Shadows/Pokemon_Crystal_Legacy#14]
But I'm pretty sure it should be DRK.

![Screenshot_20240824-210544~2](https://github.com/user-attachments/assets/434f74e0-c0f0-43f3-a95c-9b9df3556c9e)

**Comment by cRz-Shadows** [comment]
Don't know what's going on with your game but this isn't the case

![image](https://github.com/user-attachments/assets/f7c444f4-13bc-404f-9f53-b85f9a5ce8dd)

**Comment by BenjaminEHowe** [comment]
That's... fascinating. I thought it might be a simple ordering problem, but clearly it's something more complex.

I'm using [John GBAC](https://play.google.com/store/apps/details?id=com.johnemulators.johngbac) on Android -- what emulator are you using?

**Comment by cRz-Shadows** [comment]
MGBA, and it's been tested by our playtesters on multiple different emulators. Did you build from the repo or use the patch?

**Comment by BenjaminEHowe** [comment]
I used the patch. I think I've fixed the problem, but I've no idea how I caused it...

When I renamed the patched file in the GUI file manager (Linux Mint Cinnamon Edition 20.2), the hash changed to `5d680e0105be0ef5ce1fadccb1e1dbaae0dd1302`. When I renamed it via the terminal / `mv`, the hash remained `80956dfc8f617668878c36245377091622553d6d` and this bug goes away.

Any ideas what might be going on behind the scenes? I never opened the file so wouldn't expect the hash to change!

**Comment by cRz-Shadows** [comment]
There was a broken patch that was out for a small amount of time on launch (I have genuinely no idea how this happened because I made the patch with the same roms using the same site) which resulted in that. If you downloaded within the first few minutes you may have gotten that.
