### ISSUE TITLE
[Request] Implement 60fps scrolling

### ISSUE THREAD

**Issue by user18081972** [cRz-Shadows/Pokemon_Crystal_Legacy#6]
When you frame advance, you will notice that the game updates only every other frame when walking across the overworld. Essentially running at 30fps.

There are working examples of the game modded to run at 60fps.
The Pokemon Prism romhack,
and https://github.com/hyperdriveguy/pokecrystal-60fps-example

Would be cool if this could be implemented, as it helps to reduce persistence (motion) blur on modern displays.

**Comment by cRz-Shadows** [comment]
We are not going to inplement that, but you are welcome to make a fork and add it in yourself!
